all:
	g++ -o ObjectsTest ObjectsTest.cpp ObjectContainer.cpp Object.cpp Rectangle.cpp Circle.cpp Square.cpp Triangle.cpp BadSizeException.cpp BadChoiceException.cpp
debug:
	g++ -o ObjectsTest ObjectsTest.cpp ObjectContainer.cpp Object.cpp Rectangle.cpp Circle.cpp Square.cpp Triangle.cpp BadSizeException.cpp BadChoiceException.cpp -g
clean:
	rm -rf ObjectsTest
check:
	./ObjectsTest
